apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: frontend-env
          configMap:
            name: frontend-config
      containers:
        - name: todo-frontend
          image: petrishutin/todo_frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: frontend-env
              mountPath: /app/.env.production
              subPath: env.production
            - name: frontend-env
              mountPath: /app/.env.development
              subPath: env.development


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: todo
data:
  env.production: |
    VUE_APP_API_ROOT=http://10.0.0.28:8000/api/v1/
  env.development: |
    VUE_APP_API_ROOT=http://10.0.0.28:8000/api/v1/

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: todo
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }
    
    http {
      server {
        listen 80;
        server_name frontend;
        root /usr/share/nginx/html;
    
        location / {
          try_files $uri $uri/ /index.html;
        }
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: todo
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer